[package]
name = "day19"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
description = "https://adventofcode.com/2022/day/19"

[dependencies]
sscanf = "0.4.0"
pathfinding = "4.0.0"