[package]
name = "day11"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
description = "https://adventofcode.com/2022/day/11"

[dependencies]
nom = "7.1.1"
text_io = "0.1.12"
sscanf = "0.4.0"