[package]
name = "day10"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
description = "https://adventofcode.com/2022/day/10"

[dependencies]
nom = "7.1.1"
