[package]
name = "day1"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
description = "https://www.codingame.com/ide/puzzle/card-counting-when-easily-distracted"

[dependencies]
