[package]
name = "day23"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
description = "https://adventofcode.com/2022/day/23"

[dependencies]
nom = "7.1.1"
sscanf = "0.4.0"
dynamic-matrix = "0.1.1"
