[package]
name = "day25"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
description = "https://adventofcode.com/2022/day/25"

[dependencies]
pathfinding = "4.0.0"
sscanf = "0.4.0"
dynamic-matrix = "0.1.1"
